Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Ininital conditions
x     = 0.1
v     = 0.5

# Input parameters of simulation
kBT   = 0.25
gamma = 10
dt    = 0.01
t_max = 10000
freq  = 10

times, pos, vel, KE, PE = langevin_md_1d(x, v, dt, kBT, gamma, t_max, ho_en_force)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2251/4014160684.py[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m [0mfreq[0m  [0;34m=[0m [0;36m10[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0;34m[0m[0m
[0;32m---> 12[0;31m [0mtimes[0m[0;34m,[0m [0mpos[0m[0;34m,[0m [0mvel[0m[0;34m,[0m [0mKE[0m[0;34m,[0m [0mPE[0m [0;34m=[0m [0mlangevin_md_1d[0m[0;34m([0m[0mx[0m[0;34m,[0m [0mv[0m[0;34m,[0m [0mdt[0m[0;34m,[0m [0mkBT[0m[0;34m,[0m [0mgamma[0m[0;34m,[0m [0mt_max[0m[0;34m,[0m [0mho_en_force[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_2251/4165635770.py[0m in [0;36mlangevin_md_1d[0;34m(x, v, dt, kBT, gamma, t_max, en_force)[0m
[1;32m     18[0m [0;34m[0m[0m
[1;32m     19[0m         [0;31m#O-step[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 20[0;31m         [0mv[0m [0;34m=[0m [0mv[0m[0;34m*[0m[0mnp[0m[0;34m.[0m[0mexp[0m[0;34m([0m[0;34m-[0m[0mgamma[0m[0;34m*[0m[0mdt[0m[0;34m)[0m [0;34m+[0m [0mnp[0m[0;34m.[0m[0msqrt[0m[0;34m([0m[0;36m1[0m[0;34m-[0m[0mnp[0m[0;34m.[0m[0mexp[0m[0;34m([0m[0;34m-[0m[0;36m2[0m[0;34m*[0m[0mgamma[0m[0;34m*[0m[0mdt[0m[0;34m)[0m[0;34m)[0m [0;34m*[0m [0mnp[0m[0;34m.[0m[0msqrt[0m[0;34m([0m[0mkBT[0m[0;34m)[0m [0;34m*[0m [0mnormal[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     21[0m [0;34m[0m[0m
[1;32m     22[0m         [0;31m#A-step[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'normal' is not defined
NameError: name 'normal' is not defined

