Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Ininital conditions
x     = 0.1
v     = 0.5

# Input parameters of simulation
kBT   = 0.25
gamma = 10
dt    = 0.01
t_max = 10000
freq  = 10

### Define Potential
def ho_en_force(x, k=1, a=0):
    
    energy = 0.5*k*((x-a)**2) 
    force = -k*x*(x-a)
    
    return energy, force

### Runt the simulation
times, pos, vel, KE, PE = langevin_md_1d(x, v, dt, kBT, gamma, t_max, ho_en_force)


#### Plot the results
fig, ax =plt.subplots(nrows=1, ncols=2, figsize=(9,4))

bins=50

def gaussian_x(x, k, kBT): 
    return  np.exp(-k*(x**2)/(2*kBT)) / np.sqrt(2*np.pi*kBT/k)
    
def gaussian_v(v, kBT):   
    return  np.exp(-(v**2)/(2*kBT))  / np.sqrt(2*np.pi*kBT) 

x = np.linspace(min(pos), max(pos), bins)
ax[0].hist(pos, bins=bins, density=True) 
ax[0].plot(x, gaussian_x(x, k, kBT), lw=2, color='k')

v = np.linspace(min(vel), max(vel), bins)
ax[1].hist(vel, bins=bins, density=True, color='orange') 
ax[1].plot(v, gaussian_v(v, kBT), lw=2, color='k')

ax[0].set_ylabel('P(x)')
ax[1].set_ylabel('P(v)')

fig.tight_layout()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOverflowError[0m                             Traceback (most recent call last)
Cell [0;32mIn[8], line 21[0m
[1;32m     18[0m     [38;5;28;01mreturn[39;00m energy, force
[1;32m     20[0m [38;5;66;03m### Runt the simulation[39;00m
[0;32m---> 21[0m times, pos, vel, KE, PE [38;5;241m=[39m [43mlangevin_md_1d[49m[43m([49m[43mx[49m[43m,[49m[43m [49m[43mv[49m[43m,[49m[43m [49m[43mdt[49m[43m,[49m[43m [49m[43mkBT[49m[43m,[49m[43m [49m[43mgamma[49m[43m,[49m[43m [49m[43mt_max[49m[43m,[49m[43m [49m[43mho_en_force[49m[43m)[49m
[1;32m     24[0m [38;5;66;03m#### Plot the results[39;00m
[1;32m     25[0m fig, ax [38;5;241m=[39mplt[38;5;241m.[39msubplots(nrows[38;5;241m=[39m[38;5;241m1[39m, ncols[38;5;241m=[39m[38;5;241m2[39m, figsize[38;5;241m=[39m([38;5;241m9[39m,[38;5;241m4[39m))

Cell [0;32mIn[7], line 44[0m, in [0;36mlangevin_md_1d[0;34m(x, v, dt, kBT, gamma, t_max, en_force)[0m
[1;32m     42[0m pos[38;5;241m.[39mappend(x)
[1;32m     43[0m vel[38;5;241m.[39mappend(v)
[0;32m---> 44[0m KE[38;5;241m.[39mappend([38;5;241m0.5[39m [38;5;241m*[39m [43mv[49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;241;43m2[39;49m)
[1;32m     45[0m PE[38;5;241m.[39mappend(pe)
[1;32m     47[0m [38;5;66;03m# Advance time[39;00m

[0;31mOverflowError[0m: (34, 'Numerical result out of range')

