Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plotting the results
fig, (ax1, ax2) = plt.subplots(nrows=2)
ax1.plot(cumulative_probabilities[:, 0], label='Probability of A', color='blue')
ax1.plot(cumulative_probabilities[:, 1], label='Probability of B', color='red')
ax1.set_xlabel('Steps')
ax1.set_ylabel('Probability')
ax1.set_title('Approach to Equilibrium Probabilities of States A and B')
ax1.legend()
ax1.grid(True)


# Plotting the results
ax2.bar(['A', 'B'], [state_record[0]/n_steps, state_record[1]/n_steps], color=['blue', 'red'])
ax2.set_ylabel('Probability')
ax2.set_title('Equilibrium probabilities of states A and B')
fig.tight_layout()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 13[0m
[1;32m      9[0m ax1[38;5;241m.[39mgrid([38;5;28;01mTrue[39;00m)
[1;32m     12[0m [38;5;66;03m# Plotting the results[39;00m
[0;32m---> 13[0m ax2[38;5;241m.[39mbar([[38;5;124m'[39m[38;5;124mA[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mB[39m[38;5;124m'[39m], [[43mstate_record[49m[[38;5;241m0[39m][38;5;241m/[39mn_steps, state_record[[38;5;241m1[39m][38;5;241m/[39mn_steps], color[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mblue[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mred[39m[38;5;124m'[39m])
[1;32m     14[0m ax2[38;5;241m.[39mset_ylabel([38;5;124m'[39m[38;5;124mProbability[39m[38;5;124m'[39m)
[1;32m     15[0m ax2[38;5;241m.[39mset_title([38;5;124m'[39m[38;5;124mEquilibrium probabilities of states A and B[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'state_record' is not defined

